package luckyfish.programs.minepet.utils.v1_0R0.crash;

import luckyfish.programs.minepet.crash.CrashReport;

import javax.swing.*;
import java.awt.*;
import java.awt.datatransfer.StringSelection;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public class CrashDialog extends JDialog {
	private final CrashReport crashReport;
	private JPanel contentPane;
	private JTextArea CrashDescription;
	private JTextPane CrashReportDisplay;
	private JButton button1;
	private JButton buttonCopy;

	public CrashDialog(CrashReport crashReport) {
		this.crashReport = crashReport;
		setContentPane(contentPane);
		setModal(true);

		setTitle("啊哦，崩溃了啊");
		CrashDescription.setEditable(false);

		if (crashReport.getCause() instanceof OutOfMemoryError) {
			CrashDescription.setText("这这这不是我们的错！是你电脑内存不够！");
		} else if (!crashReport.isFatal()) {
			CrashDescription.setText("好吧，我们中间出了点小错误=w=如果你注意到更多的话请将它报告给我的主人！");
		} else {
			CrashDescription.setText("好吧我觉得我没法继续进行下去了QwQ我先走了哈");

			addWindowStateListener(new WindowAdapter() {
				@Override
				public void windowClosed(WindowEvent e) {
					System.exit(1);
				}
			});
		}
		CrashReportDisplay.setEditable(false);
		CrashReportDisplay.setText(crashReport.toString() + System.getProperty("line.separator") + "p.s. 错误报告同样也能在启动器同目录下找到喔:)");

		button1.setText(crashReport.isFatal() ? "退出" : "关闭");
		button1.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				CrashDialog.this.dispose();
			}
		});
		buttonCopy.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				StringSelection stringSelection = new StringSelection(crashReport.toString());
				Toolkit.getDefaultToolkit().getSystemClipboard().setContents(stringSelection, stringSelection);
			}
		});
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		contentPane = new JPanel();
		contentPane.setLayout(new BorderLayout(0, 0));
		final JPanel panel1 = new JPanel();
		panel1.setLayout(new BorderLayout(0, 0));
		contentPane.add(panel1, BorderLayout.NORTH);
		CrashDescription = new JTextArea();
		panel1.add(CrashDescription, BorderLayout.CENTER);
		final JPanel panel2 = new JPanel();
		panel2.setLayout(new BorderLayout(0, 0));
		contentPane.add(panel2, BorderLayout.CENTER);
		CrashReportDisplay = new JTextPane();
		panel2.add(CrashReportDisplay, BorderLayout.NORTH);
		button1 = new JButton();
		button1.setText("Button");
		panel2.add(button1, BorderLayout.EAST);
		buttonCopy = new JButton();
		buttonCopy.setText("复制错误报告");
		panel2.add(buttonCopy, BorderLayout.WEST);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return contentPane;
	}
}
