/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class luckyfish_programs_minepet_pet_v1_0R0_display_PetWindow */

#ifndef _Included_luckyfish_programs_minepet_pet_v1_0R0_display_PetWindow
#define _Included_luckyfish_programs_minepet_pet_v1_0R0_display_PetWindow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     luckyfish_programs_minepet_pet_v1_0R0_display_PetWindow
 * Method:    getWindowID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_luckyfish_programs_minepet_pet_v1_10R0_display_PetWindow_getWindowID
  (JNIEnv *, jclass);

/*
 * Class:     luckyfish_programs_minepet_pet_v1_0R0_display_PetWindow
 * Method:    displayAndMaskWindow
 * Signature: (Ljava/awt/image/BufferedImage;J)V
 */
JNIEXPORT void JNICALL Java_luckyfish_programs_minepet_pet_v1_10R0_display_PetWindow_displayAndMaskWindow
  (JNIEnv *, jclass, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
